---
title: "Reproducible Research: Peer Assessment 1"
output:
  html_document:
    keep_md: true
---
# Project 1
# By MAVC 18/04/2015

## Loading and preprocessing the data
```{r}
library(ggplot2)
activity <- read.csv("activity.csv")
activity$date <- as.Date(activity$date)
activity$interval <- (activity$interval%/%100)*60 + activity$interval%%100
```

## What is mean total number of steps taken per day?
```{r}
total_steps_per_day <-sapply(split(activity$steps, f=activity$date, drop = FALSE), sum, na.rm = TRUE)
hist(total_steps_per_day, breaks = 20, main = "Total number of steps per Day", xlab = "Number of Steps")
mean_steps_per_day <-sapply(split(activity$steps, f=activity$date, drop = FALSE), mean, na.rm = TRUE)
median_steps_per_day <-sapply(split(activity$steps, f=activity$date, drop = FALSE), median, na.rm = TRUE)
mean(activity$steps, na.rm = TRUE)
median(activity$steps, na.rm = TRUE)
summary_analysis <- data.frame(mean_steps_per_day,median_steps_per_day)
summary_analysis
```

## What is the average daily activity pattern?
```{r}
mean_daily_activity_pattern <-sapply(split(activity$steps, f=activity$interval, drop = FALSE), mean, na.rm = TRUE)
plot(names(mean_daily_activity_pattern), mean_daily_activity_pattern, type = "l", main = "Mean Daily Activity Pattern", xlab = "Day in minutes", ylab = "Average steps across all days")
maximun_activity_interval <- which.max(mean_daily_activity_pattern)
maximun_activity_interval
```

## Imputing missing values
```{r}
number_NA <- sum(is.na(activity))
number_NA
#New Data Frame
original_activity <- activity
#Method to replace NAs values by the most common number of steps recorded
most_common_number_steps <- which.max(table(activity$steps))
activity[is.na(activity)] <- as.numeric(names(most_common_number_steps))
total_steps_per_day_noNA <-sapply(split(activity$steps, f=activity$date, drop = FALSE), sum, na.rm = TRUE)
hist(total_steps_per_day_noNA, breaks = 20, main = "Total number of steps per Day", xlab = "Number of Steps")
mean_steps_per_day_noNA <-sapply(split(activity$steps, f=activity$date, drop = FALSE), mean, na.rm = TRUE)
median_steps_per_day_noNA <-sapply(split(activity$steps, f=activity$date, drop = FALSE), median, na.rm = TRUE)
summary_analysis <- data.frame(mean_steps_per_day_noNA, median_steps_per_day_noNA)
summary_analysis
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
activity$day <- weekdays(activity$date)
activity[activity$day == "Monday",4] <- "weekday"
activity[activity$day == "Tuesday",4] <- "weekday"
activity[activity$day == "Wednesday",4] <- "weekday"
activity[activity$day == "Thursday",4] <- "weekday"
activity[activity$day == "Friday",4] <- "weekday"
activity[activity$day == "Saturday",4] <- "weekend"
activity[activity$day == "Sunday",4] <- "weekend"
activity$day <- as.factor(activity$day)
weekends <- activity[which(activity$day == 'weekday'),]
weekdays <- activity[which(activity$day == 'weekend'),]
mean_weekdays_activity_pattern <-sapply(split(weekdays$steps, f=weekdays$interval, drop = FALSE), mean, na.rm = TRUE)
mean_weekends_activity_pattern <-sapply(split(weekends$steps, f=weekends$interval, drop = FALSE), mean, na.rm = TRUE)
par(mfrow = c(1, 2))
plot(names(mean_weekdays_activity_pattern), mean_weekdays_activity_pattern, type = "l", main = "Mean Daily Activity Pattern", xlab = "Day in minutes", ylab = "Average steps across all days")
plot(names(mean_weekends_activity_pattern), mean_weekends_activity_pattern, type = "l", main = "Mean Daily Activity Pattern", xlab = "Day in minutes", ylab = "Average steps across all days")
```